"""empty message

Revision ID: dedd0851d914
Revises: bc19102fa037
Create Date: 2018-06-27 06:10:58.253994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dedd0851d914'
down_revision = 'bc19102fa037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.String(length=60), nullable=True),
    sa.Column('sex', sa.String(length=60), nullable=True),
    sa.Column('age', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id')
    )
    op.drop_index('animal_id', table_name='streetanimals')
    op.drop_table('streetanimals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streetanimals',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('animal_id', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('sex', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('age', mysql.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8mb4_0900_ai_ci',
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.create_index('animal_id', 'streetanimals', ['animal_id'], unique=True)
    op.drop_table('animals')
    # ### end Alembic commands ###
